const $=(s,p=document)=>p.querySelector(s);const $$=(s,p=document)=>[...p.querySelectorAll(s)];
const phone='919422062887';
let req={service:'',media:'',size:'',qty:'',finish:'',branch:'',deadline:'',name:'',note:''};
function initTheme(){const saved=localStorage.getItem('cbc-theme')||'light';document.documentElement.dataset.theme=saved;$$('[data-theme-toggle]').forEach(b=>b.textContent=saved==='dark'?'☀':'◐');$$('[data-theme-toggle]').forEach(b=>b.addEventListener('click',()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('cbc-theme',n);$$('[data-theme-toggle]').forEach(x=>x.textContent=n==='dark'?'☀':'◐')}));}
function initNav(){const btn=$('#menuBtn'),links=$('#navLinks');btn?.addEventListener('click',()=>{links.classList.toggle('open');btn.classList.toggle('open')});$$('.nav-links a').forEach(a=>a.addEventListener('click',()=>links?.classList.remove('open')));}
function scrollMotion(){let last=scrollY;const root=document.documentElement;function tick(){const hero=$('.printer-hero');if(hero){const r=hero.getBoundingClientRect();const p=Math.min(1,Math.max(0,(0-r.top)/(r.height*0.75)));root.style.setProperty('--print-progress',p.toFixed(3));document.body.classList.toggle('shred-mode',scrollY<last&&scrollY<260)}last=scrollY;$$('.print-sheet').forEach(el=>{const r=el.getBoundingClientRect();if(r.top<innerHeight*.86)el.classList.add('visible')});}tick();addEventListener('scroll',tick,{passive:true});}
function serviceCard(s){return `<article class="service-card"><div class="service-media"><img src="${s.image}" alt="${s.title}"><span>${s.tag}</span></div><div class="service-body"><h3>${s.title}</h3><p>${s.desc}</p><ul>${s.items.map(i=>`<li>${i}</li>`).join('')}</ul><a href="print-request.html" class="card-link">Request this service</a></div></article>`;}
function renderServices(){if(!window.CBC_DATA)return;const full=$('#servicesGrid'),home=$('#homeServices');if(full)full.innerHTML=CBC_DATA.services.map(serviceCard).join('');if(home)home.innerHTML=CBC_DATA.services.slice(0,6).map(serviceCard).join('');}
function renderGallery(){const wrap=$('#galleryGrid');if(!wrap||!window.CBC_DATA)return;wrap.innerHTML=CBC_DATA.gallery.map(g=>`<article class="gallery-card"><img src="${g.image}" alt="${g.title}"><b>${g.title}</b></article>`).join('');}
function renderMedia(){const body=$('#mediaBody'),search=$('#mediaSearch'),filter=$('#mediaFilter');if(!body||!window.CBC_DATA)return;const types=[...new Set(CBC_DATA.media.map(m=>m.type))];if(filter)filter.innerHTML='<option value="all">All categories</option>'+types.map(t=>`<option value="${t}">${t}</option>`).join('');function draw(){const q=(search?.value||'').toLowerCase(),f=filter?.value||'all';const rows=CBC_DATA.media.filter(m=>(f==='all'||m.type===f)&&Object.values(m).join(' ').toLowerCase().includes(q));body.innerHTML=rows.map(m=>`<tr><td data-label="Material">${m.name}</td><td data-label="GSM">${m.gsm}</td><td data-label="Size">${m.size}</td><td data-label="Category">${m.type}</td><td data-label="Rate"><strong>${m.price}</strong></td></tr>`).join('');}search?.addEventListener('input',draw);filter?.addEventListener('change',draw);draw();}
function renderSizes(){const wrap=$('#sizeGrid');if(!wrap||!window.CBC_DATA)return;wrap.innerHTML=CBC_DATA.sizes.map(s=>`<article class="size-card"><b>${s.name}</b><span>${s.mm}</span><p>${s.use}</p></article>`).join('');}
function renderBranches(){const wrap=$('#branchGrid');if(!wrap||!window.CBC_DATA)return;wrap.innerHTML=CBC_DATA.branches.map(b=>`<article class="branch-card"><div class="branch-copy"><span class="tag">${b.label}</span><h3>${b.name}</h3><p>${b.address}</p><a class="ghost" href="https://www.google.com/maps/search/${encodeURIComponent(b.map)}" target="_blank" rel="noopener">Open directions</a></div><iframe loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="https://maps.google.com/maps?q=${encodeURIComponent(b.map)}&t=&z=15&ie=UTF8&iwloc=&output=embed"></iframe></article>`).join('');}
function initPrintForm(){const services=$('#serviceOptions'),media=$('#mediaOptions');if(!services||!window.CBC_DATA)return;services.innerHTML=CBC_DATA.services.map(s=>`<button class="option" data-key="service" data-val="${s.title}"><b>${s.title}</b><small>${s.tag}</small></button>`).join('');media.innerHTML=CBC_DATA.media.map(m=>`<button class="option" data-key="media" data-val="${m.name} · ${m.gsm} · ${m.size} · ${m.price}"><b>${m.name}</b><small>${m.gsm} · ${m.size} · ${m.price}</small></button>`).join('');const steps=$$('.step-btn'),panels=$$('.form-step'),bar=$('#progressBar');function collect(){$$('[data-req]').forEach(i=>req[i.dataset.req]=i.value)}function summary(){collect();const box=$('#requestSummary');if(box)box.innerHTML=`<dl><dt>Service</dt><dd>${req.service||'Not selected'}</dd><dt>Paper / media</dt><dd>${req.media||'Not selected'}</dd><dt>Size</dt><dd>${req.size||'-'}</dd><dt>Quantity</dt><dd>${req.qty||'-'}</dd><dt>Finishing</dt><dd>${req.finish||'-'}</dd><dt>Branch</dt><dd>${req.branch||'-'}</dd><dt>Deadline</dt><dd>${req.deadline||'-'}</dd><dt>Name</dt><dd>${req.name||'-'}</dd><dt>Notes</dt><dd>${req.note||'-'}</dd></dl>`;}function show(i){steps.forEach((s,k)=>s.classList.toggle('active',k===i));panels.forEach((p,k)=>p.classList.toggle('active',k===i));if(bar)bar.style.width=`${((i+1)/panels.length)*100}%`;summary();}steps.forEach((s,i)=>s.addEventListener('click',()=>show(i)));$$('.next-step').forEach(b=>b.addEventListener('click',()=>show(Math.min(panels.length-1,steps.findIndex(s=>s.classList.contains('active'))+1))));$$('.prev-step').forEach(b=>b.addEventListener('click',()=>show(Math.max(0,steps.findIndex(s=>s.classList.contains('active'))-1))));document.addEventListener('click',e=>{const o=e.target.closest('.option');if(!o)return;req[o.dataset.key]=o.dataset.val;$$(`.option[data-key="${o.dataset.key}"]`).forEach(x=>x.classList.remove('selected'));o.classList.add('selected');summary();});$$('[data-req]').forEach(i=>i.addEventListener('input',summary));$('#waBtn')?.addEventListener('click',()=>{collect();const msg=`Hello Classic Business Centre, I want to place a print request.%0A%0AService: ${encodeURIComponent(req.service||'-')}%0APaper / Media: ${encodeURIComponent(req.media||'-')}%0ASize: ${encodeURIComponent(req.size||'-')}%0AQuantity: ${encodeURIComponent(req.qty||'-')}%0AFinishing: ${encodeURIComponent(req.finish||'-')}%0ABranch: ${encodeURIComponent(req.branch||'-')}%0ADeadline: ${encodeURIComponent(req.deadline||'-')}%0AName: ${encodeURIComponent(req.name||'-')}%0ANotes: ${encodeURIComponent(req.note||'-')}%0A%0AI will attach the print file here.`;window.open(`https://wa.me/${phone}?text=${msg}`,'_blank');});show(0);}
document.addEventListener('DOMContentLoaded',()=>{initTheme();initNav();scrollMotion();renderServices();renderGallery();renderMedia();renderSizes();renderBranches();initPrintForm();});